"""
report.py
---------
Builds a single portable HTML report with charts embedded as base64 images,
so the whole thing can be emailed or opened offline with no dependencies.
"""

from __future__ import annotations

import base64
import os


def _img_tag(path: str | None) -> str:
    if not path or not os.path.exists(path):
        return "<p><em>Not available for this site.</em></p>"
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("ascii")
    return f'<img src="data:image/png;base64,{encoded}" style="max-width:100%;">'


def build_html_report(
    site_url: str,
    stats: dict,
    chart_paths: dict[str, str | None],
    output_path: str,
) -> str:
    stats_rows = "".join(
        f"<tr><td>{key.replace('_', ' ').title()}</td><td>{value}</td></tr>"
        for key, value in stats.items()
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>WordPress Analytics Report — {site_url}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 900px;
          margin: 40px auto; padding: 0 20px; color: #1e1e1e; }}
  h1 {{ font-size: 1.6rem; }}
  h2 {{ margin-top: 2.5rem; border-bottom: 2px solid #eee; padding-bottom: .3rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  td {{ padding: 6px 10px; border-bottom: 1px solid #eee; }}
  td:first-child {{ color: #555; }}
  .chart {{ margin: 1.5rem 0; }}
  footer {{ margin-top: 3rem; color: #888; font-size: .85rem; }}
</style>
</head>
<body>
  <h1>WordPress Analytics Report</h1>
  <p><strong>Site:</strong> {site_url}</p>

  <h2>Summary</h2>
  <table>{stats_rows}</table>

  <h2>Posting Frequency Over Time</h2>
  <div class="chart">{_img_tag(chart_paths.get("posts_per_month"))}</div>

  <h2>Most Active Categories</h2>
  <div class="chart">{_img_tag(chart_paths.get("top_categories"))}</div>

  <h2>Most Prolific Authors</h2>
  <div class="chart">{_img_tag(chart_paths.get("top_authors"))}</div>

  <h2>Average Comments per Post, by Category</h2>
  <div class="chart">{_img_tag(chart_paths.get("avg_comments_by_category"))}</div>

  <footer>Generated by wp-analytics-reporter</footer>
</body>
</html>"""

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    return output_path
